// HT-41: generate the in-app copy of RELEASE_NOTES.md.
//
//   node scripts/release-notes.mjs          rewrite constants/releaseNotes.generated.ts
//   node scripts/release-notes.mjs --check  fail if the committed file is stale
//
// /whats-new renders the notes for the version a host is running from the
// generated module; RELEASE_NOTES.md at the repository root stays the one
// place the notes are written. CI runs --check so the two cannot drift: edit
// the Markdown, run `npm run release-notes`, commit both.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parseReleaseNotes } from './lib/releaseNotes.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(here, '..', '..', 'RELEASE_NOTES.md');
const target = path.resolve(here, '..', 'constants', 'releaseNotes.generated.ts');
const check = process.argv.includes('--check');

const sections = parseReleaseNotes(readFileSync(source, 'utf8'));
if (sections.length === 0) {
  console.error(`${path.relative(process.cwd(), source)} has no "## vX.Y.Z" section`);
  process.exit(1);
}

const generated = [
  '// GENERATED by web/scripts/release-notes.mjs from RELEASE_NOTES.md (HT-41).',
  '// Do not edit: change the Markdown and run `npm run release-notes`.',
  '',
  'export type ReleaseNote = {',
  '  /** Tag with the v prefix, e.g. v1.5.0 */',
  '  version: string;',
  '  /** Text after the dash in the heading, usually the release date; null before release */',
  '  date: string | null;',
  '  /** Markdown body of the section */',
  '  body: string;',
  '};',
  '',
  `export const RELEASE_NOTES: ReleaseNote[] = ${JSON.stringify(sections, null, 2)};`,
  '',
].join('\n');

let existing = null;
try {
  existing = readFileSync(target, 'utf8').replace(/\r\n/g, '\n');
} catch {
  existing = null;
}

if (check) {
  if (existing !== generated) {
    console.error(
      `${path.relative(process.cwd(), target)} is out of date with RELEASE_NOTES.md; run "npm run release-notes" and commit the result`,
    );
    process.exit(1);
  }
  console.log(`release notes up to date (${sections.length} release${sections.length === 1 ? '' : 's'}, newest ${sections[0].version})`);
} else {
  writeFileSync(target, generated);
  console.log(`wrote ${path.relative(process.cwd(), target)} (${sections.length} release${sections.length === 1 ? '' : 's'}, newest ${sections[0].version})`);
}
