

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."clients" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "email" "text",
    "phone" "text",
    "address" "text",
    "updated_at" timestamp with time zone,
    "notes" "text",
    "city" "text",
    "state" "text",
    "zip" numeric,
    "tag" "text"
);


ALTER TABLE "public"."clients" OWNER TO "postgres";


ALTER TABLE "public"."clients" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Clients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "business_name" "text",
    "address" "text",
    "email" "text",
    "phone" "text",
    "ein" "text",
    "updated_at" timestamp with time zone,
    "logo_url" "text"
);


ALTER TABLE "public"."company" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."company_attachments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "url" "text",
    "uploaded_by" timestamp with time zone,
    "updated_by" timestamp with time zone,
    "file_type" "text",
    "file_size" bigint,
    "company_id" bigint,
    "file_data" "text",
    "is_logo" boolean
);


ALTER TABLE "public"."company_attachments" OWNER TO "postgres";


ALTER TABLE "public"."company_attachments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_attachments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."company" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."email_integrations" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "provider" character varying,
    "email" character varying,
    "access_token" "text",
    "refresh_token" "text",
    "grant_id" "text",
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."email_integrations" OWNER TO "postgres";


ALTER TABLE "public"."email_integrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."email_integrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."invoice_items" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "invoice_id" bigint,
    "description" "text",
    "quantity" numeric,
    "unit_price" numeric,
    "amount" numeric,
    "type" "text",
    "item_id" bigint,
    "material_id" bigint,
    "service_id" bigint
);


ALTER TABLE "public"."invoice_items" OWNER TO "postgres";


ALTER TABLE "public"."invoice_items" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."invoice_items_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."invoices" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "job_id" bigint,
    "client_id" bigint,
    "invoice_number" character varying,
    "issue_date" "date",
    "due_date" "date",
    "subtotal" numeric,
    "tax_rate" numeric,
    "tax_amount" numeric,
    "total" numeric,
    "notes" "text",
    "status" "text",
    "user_id" bigint
);


ALTER TABLE "public"."invoices" OWNER TO "postgres";


ALTER TABLE "public"."invoices" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."invoices_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_calender_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" bigint,
    "event_id" "text",
    "calendar_id" "text",
    "last_synced" timestamp with time zone,
    "sync_status" character varying,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."job_calender_events" OWNER TO "postgres";


ALTER TABLE "public"."job_calender_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job_calender_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_costs" (
    "uid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" bigint,
    "description" "text",
    "quantity" numeric,
    "price" numeric,
    "amount" numeric,
    "type" "text",
    "created_by" "uuid",
    "updated_by" timestamp with time zone,
    "material_id" bigint,
    "service_id" bigint
);


ALTER TABLE "public"."job_costs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "title" "text",
    "description" "text",
    "status" "text",
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "client_id" bigint,
    "calendar_event_id" "text"
);


ALTER TABLE "public"."jobs" OWNER TO "postgres";


COMMENT ON COLUMN "public"."jobs"."calendar_event_id" IS 'Tracks the gcal event for quick retrieval/update/deletion.';



CREATE TABLE IF NOT EXISTS "public"."jobs_attachments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" bigint,
    "name" "text",
    "url" "text",
    "uploaded_by" timestamp with time zone,
    "updated_by" timestamp with time zone,
    "type" "text",
    "size" bigint
);


ALTER TABLE "public"."jobs_attachments" OWNER TO "postgres";


ALTER TABLE "public"."jobs_attachments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."jobs_attachments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."jobs" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."jobs_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."materials" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "name" "text",
    "description" "text",
    "cost" numeric,
    "unit" numeric,
    "quantity" numeric,
    "category" "text",
    "supplier" "text",
    "supplier_id" bigint,
    "is_active" boolean,
    "reorder_level" numeric,
    "Total_cost" numeric
);


ALTER TABLE "public"."materials" OWNER TO "postgres";


ALTER TABLE "public"."materials" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."materials_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "display_name" "text",
    "email" character varying,
    "password" character varying,
    "phone" numeric,
    "role" character varying
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."services" (
    "uid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "name" "text",
    "description" "text",
    "rate" numeric,
    "unit" numeric,
    "category" "text",
    "is_active" boolean,
    "Total_cost" numeric
);


ALTER TABLE "public"."services" OWNER TO "postgres";


ALTER TABLE "public"."services" ALTER COLUMN "uid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "roles" "text"
);


ALTER TABLE "public"."user_roles" OWNER TO "postgres";


ALTER TABLE "public"."user_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."company_attachments"
    ADD CONSTRAINT "company_attachments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."company"
    ADD CONSTRAINT "company_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."email_integrations"
    ADD CONSTRAINT "email_integrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."job_calender_events"
    ADD CONSTRAINT "job_calender_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."job_costs"
    ADD CONSTRAINT "job_costs_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."jobs_attachments"
    ADD CONSTRAINT "jobs_attachments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_calendar_event_id_key" UNIQUE ("calendar_event_id");



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."materials"
    ADD CONSTRAINT "materials_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "services_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "on-job-update" AFTER INSERT OR DELETE OR UPDATE ON "public"."jobs" FOR EACH ROW EXECUTE FUNCTION "supabase_functions"."http_request"('https://evgopevhaapzyvqulwjb.supabase.co/functions/v1/upsert-calendar-event', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z29wZXZoYWFwenl2cXVsd2piIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDQzMTM4MywiZXhwIjoyMDU2MDA3MzgzfQ.t4o9hujb9DaV8Em-4hEfazhk_WzashFn4QnoxzZ9jSc"}', '{}', '5000');



ALTER TABLE ONLY "public"."company_attachments"
    ADD CONSTRAINT "company_attachments_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."company"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "public"."materials"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."services"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("uid") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("uid") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."job_costs"
    ADD CONSTRAINT "job_costs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."job_costs"
    ADD CONSTRAINT "job_costs_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."job_costs"
    ADD CONSTRAINT "job_costs_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "public"."materials"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."job_costs"
    ADD CONSTRAINT "job_costs_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."services"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."jobs_attachments"
    ADD CONSTRAINT "jobs_attachments_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("uid") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("uid") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE;



CREATE POLICY "  Allow insert for authenticated users" ON "public"."email_integrations" FOR INSERT WITH CHECK (true);



CREATE POLICY "  Allow update for authenticated users" ON "public"."email_integrations" FOR UPDATE USING (true);



CREATE POLICY "Allow authenticated users to select clients" ON "public"."clients" FOR SELECT USING (true);



CREATE POLICY "Allow authenticated users to select clients" ON "public"."company" FOR SELECT USING (true);



CREATE POLICY "Allow authenticated users to select clients" ON "public"."company_attachments" FOR SELECT USING (true);



CREATE POLICY "Allow authenticated users to select clients" ON "public"."email_integrations" FOR SELECT USING (true);



CREATE POLICY "Allow authenticated users to select clients" ON "public"."invoice_items" FOR SELECT USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."clients" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."company" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."company_attachments" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."email_integrations" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."invoice_items" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."job_calender_events" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."job_costs" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."jobs" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."jobs_attachments" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."materials" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."profiles" FOR DELETE USING (true);



CREATE POLICY "Allow delete for authenticated users" ON "public"."services" FOR DELETE USING (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."clients" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."company" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."company_attachments" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."invoice_items" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."job_calender_events" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."job_costs" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."jobs" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."jobs_attachments" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."materials" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."profiles" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated users" ON "public"."services" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."job_calender_events" FOR SELECT USING (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."job_costs" FOR SELECT USING (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."jobs" FOR SELECT USING (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."jobs_attachments" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."materials" FOR SELECT USING (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."services" FOR SELECT USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."clients" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."company" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."company_attachments" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."invoice_items" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."job_calender_events" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."job_costs" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."jobs" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."jobs_attachments" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."materials" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."profiles" FOR UPDATE USING (true);



CREATE POLICY "Allow update for authenticated users" ON "public"."services" FOR UPDATE USING (true);



CREATE POLICY "Enable all operations for authenticated users" ON "public"."clients" USING (("auth"."uid"() = "auth"."uid"())) WITH CHECK (("auth"."uid"() = "auth"."uid"()));



CREATE POLICY "Enable all operations for authenticated users" ON "public"."jobs_attachments" USING (true);



CREATE POLICY "Users can create their own invoices" ON "public"."invoices" FOR INSERT WITH CHECK (true);



CREATE POLICY "Users can delete their own invoices" ON "public"."invoices" FOR DELETE USING (true);



CREATE POLICY "Users can update their own invoices" ON "public"."invoices" FOR UPDATE USING (true);



CREATE POLICY "Users can view their own invoices" ON "public"."invoices" FOR SELECT USING (true);



ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company_attachments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."email_integrations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."invoice_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."invoices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_calender_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_costs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."jobs_attachments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."materials" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";









GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."clients" TO "anon";
GRANT ALL ON TABLE "public"."clients" TO "authenticated";
GRANT ALL ON TABLE "public"."clients" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Clients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Clients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Clients_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."company" TO "anon";
GRANT ALL ON TABLE "public"."company" TO "authenticated";
GRANT ALL ON TABLE "public"."company" TO "service_role";



GRANT ALL ON TABLE "public"."company_attachments" TO "anon";
GRANT ALL ON TABLE "public"."company_attachments" TO "authenticated";
GRANT ALL ON TABLE "public"."company_attachments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_attachments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_attachments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_attachments_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_uid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_uid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_uid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."email_integrations" TO "anon";
GRANT ALL ON TABLE "public"."email_integrations" TO "authenticated";
GRANT ALL ON TABLE "public"."email_integrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."email_integrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."email_integrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."email_integrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."invoice_items" TO "anon";
GRANT ALL ON TABLE "public"."invoice_items" TO "authenticated";
GRANT ALL ON TABLE "public"."invoice_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."invoice_items_uid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."invoice_items_uid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."invoice_items_uid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."invoices" TO "anon";
GRANT ALL ON TABLE "public"."invoices" TO "authenticated";
GRANT ALL ON TABLE "public"."invoices" TO "service_role";



GRANT ALL ON SEQUENCE "public"."invoices_uid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."invoices_uid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."invoices_uid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_calender_events" TO "anon";
GRANT ALL ON TABLE "public"."job_calender_events" TO "authenticated";
GRANT ALL ON TABLE "public"."job_calender_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job_calender_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job_calender_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job_calender_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_costs" TO "anon";
GRANT ALL ON TABLE "public"."job_costs" TO "authenticated";
GRANT ALL ON TABLE "public"."job_costs" TO "service_role";



GRANT ALL ON TABLE "public"."jobs" TO "anon";
GRANT ALL ON TABLE "public"."jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs" TO "service_role";



GRANT ALL ON TABLE "public"."jobs_attachments" TO "anon";
GRANT ALL ON TABLE "public"."jobs_attachments" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs_attachments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jobs_attachments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jobs_attachments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jobs_attachments_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jobs_uid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jobs_uid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jobs_uid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."materials" TO "anon";
GRANT ALL ON TABLE "public"."materials" TO "authenticated";
GRANT ALL ON TABLE "public"."materials" TO "service_role";



GRANT ALL ON SEQUENCE "public"."materials_uid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."materials_uid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."materials_uid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."services" TO "anon";
GRANT ALL ON TABLE "public"."services" TO "authenticated";
GRANT ALL ON TABLE "public"."services" TO "service_role";



GRANT ALL ON SEQUENCE "public"."services_uid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_uid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_uid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
