drop policy "Allow delete for authenticated users" on "public"."job_calender_events";

drop policy "Allow insert for authenticated users" on "public"."job_calender_events";

drop policy "Allow select for authenticated users" on "public"."job_calender_events";

drop policy "Allow update for authenticated users" on "public"."job_calender_events";

revoke delete on table "public"."job_calender_events" from "anon";

revoke insert on table "public"."job_calender_events" from "anon";

revoke references on table "public"."job_calender_events" from "anon";

revoke select on table "public"."job_calender_events" from "anon";

revoke trigger on table "public"."job_calender_events" from "anon";

revoke truncate on table "public"."job_calender_events" from "anon";

revoke update on table "public"."job_calender_events" from "anon";

revoke delete on table "public"."job_calender_events" from "authenticated";

revoke insert on table "public"."job_calender_events" from "authenticated";

revoke references on table "public"."job_calender_events" from "authenticated";

revoke select on table "public"."job_calender_events" from "authenticated";

revoke trigger on table "public"."job_calender_events" from "authenticated";

revoke truncate on table "public"."job_calender_events" from "authenticated";

revoke update on table "public"."job_calender_events" from "authenticated";

revoke delete on table "public"."job_calender_events" from "service_role";

revoke insert on table "public"."job_calender_events" from "service_role";

revoke references on table "public"."job_calender_events" from "service_role";

revoke select on table "public"."job_calender_events" from "service_role";

revoke trigger on table "public"."job_calender_events" from "service_role";

revoke truncate on table "public"."job_calender_events" from "service_role";

revoke update on table "public"."job_calender_events" from "service_role";

alter table "public"."job_calender_events" drop constraint "job_calender_events_pkey";

drop index if exists "public"."job_calender_events_pkey";

drop table "public"."job_calender_events";

create table "public"."job_calendar_events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "job_id" bigint,
    "event_id" text,
    "calendar_id" text,
    "last_synced" timestamp with time zone,
    "sync_status" character varying,
    "updated_at" timestamp with time zone,
    "organization_id" uuid
);


alter table "public"."job_calendar_events" enable row level security;

alter table "public"."clients" add column "organization_id" uuid;

alter table "public"."company" add column "organization_id" uuid;

alter table "public"."company_attachments" add column "organization_id" uuid;

alter table "public"."invoice_items" add column "organization_id" uuid;

alter table "public"."invoices" add column "organization_id" uuid;

alter table "public"."job_costs" add column "organization_id" uuid;

alter table "public"."jobs" add column "organization_id" uuid;

alter table "public"."jobs_attachments" add column "organization_id" uuid;

alter table "public"."materials" add column "organization_id" uuid;

alter table "public"."services" add column "organization_id" uuid;

CREATE INDEX idx_clients_organization_id ON public.clients USING btree (organization_id);

CREATE INDEX idx_company_attachments_organization_id ON public.company_attachments USING btree (organization_id);

CREATE INDEX idx_company_organization_id ON public.company USING btree (organization_id);

CREATE INDEX idx_invoice_items_organization_id ON public.invoice_items USING btree (organization_id);

CREATE INDEX idx_invoices_organization_id ON public.invoices USING btree (organization_id);

CREATE INDEX idx_job_calendar_events_organization_id ON public.job_calendar_events USING btree (organization_id);

CREATE INDEX idx_job_costs_organization_id ON public.job_costs USING btree (organization_id);

CREATE INDEX idx_jobs_attachments_organization_id ON public.jobs_attachments USING btree (organization_id);

CREATE INDEX idx_jobs_organization_id ON public.jobs USING btree (organization_id);

CREATE INDEX idx_materials_organization_id ON public.materials USING btree (organization_id);

CREATE INDEX idx_services_organization_id ON public.services USING btree (organization_id);

CREATE UNIQUE INDEX job_calender_events_pkey ON public.job_calendar_events USING btree (id);

alter table "public"."job_calendar_events" add constraint "job_calender_events_pkey" PRIMARY KEY using index "job_calender_events_pkey";

alter table "public"."clients" add constraint "clients_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."clients" validate constraint "clients_organization_id_fkey";

alter table "public"."company" add constraint "company_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."company" validate constraint "company_organization_id_fkey";

alter table "public"."company_attachments" add constraint "company_attachments_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."company_attachments" validate constraint "company_attachments_organization_id_fkey";

alter table "public"."invoice_items" add constraint "invoice_items_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."invoice_items" validate constraint "invoice_items_organization_id_fkey";

alter table "public"."invoices" add constraint "invoices_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."invoices" validate constraint "invoices_organization_id_fkey";

alter table "public"."job_calendar_events" add constraint "job_calendar_events_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."job_calendar_events" validate constraint "job_calendar_events_organization_id_fkey";

alter table "public"."job_costs" add constraint "job_costs_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."job_costs" validate constraint "job_costs_organization_id_fkey";

alter table "public"."jobs" add constraint "jobs_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."jobs" validate constraint "jobs_organization_id_fkey";

alter table "public"."jobs_attachments" add constraint "jobs_attachments_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."jobs_attachments" validate constraint "jobs_attachments_organization_id_fkey";

alter table "public"."materials" add constraint "materials_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."materials" validate constraint "materials_organization_id_fkey";

alter table "public"."services" add constraint "services_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL not valid;

alter table "public"."services" validate constraint "services_organization_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.auto_set_organization_id()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  user_org_id UUID;
  user_role user_role;
BEGIN
  -- Get user's role first
  SELECT role INTO user_role FROM user_profiles WHERE id = auth.uid();
  
  -- Superusers can explicitly set any organization_id, others are auto-assigned
  IF NEW.organization_id IS NULL OR user_role != 'superuser' THEN
    
    -- For superusers with no explicit org_id, don't auto-assign (leave NULL)
    IF user_role = 'superuser' AND NEW.organization_id IS NULL THEN
      -- Leave organization_id as NULL for superusers unless explicitly set
      RETURN NEW;
    END IF;
    
    -- For regular users, get their organization from active membership
    SELECT organization_id INTO user_org_id
    FROM organization_memberships
    WHERE user_id = auth.uid()
    AND is_active = true
    ORDER BY 
      CASE WHEN role = 'admin' THEN 1
           ELSE 2 END
    LIMIT 1;
    
    -- Fall back to user_profiles if no membership found (backward compatibility)
    IF user_org_id IS NULL THEN
      SELECT organization_id INTO user_org_id
      FROM user_profiles
      WHERE id = auth.uid()
      AND role != 'superuser'; -- Don't use user_profiles org for superusers
    END IF;
    
    -- Only set if we found an organization
    IF user_org_id IS NOT NULL THEN
      NEW.organization_id := user_org_id;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_organizations()
 RETURNS uuid[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT 
    CASE 
      WHEN is_superuser() THEN ARRAY[]::UUID[]  -- Empty array for superusers
      ELSE (
        SELECT ARRAY_AGG(organization_id)
        FROM organization_memberships
        WHERE user_id = auth.uid()
        AND is_active = true
      )
    END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_primary_organization()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT 
    CASE 
      WHEN is_superuser() THEN NULL  -- Superusers don't have a primary org
      ELSE (
        SELECT organization_id
        FROM organization_memberships
        WHERE user_id = auth.uid()
        AND is_active = true
        ORDER BY 
          CASE WHEN role = 'admin' THEN 1
               ELSE 2 END
        LIMIT 1
      )
    END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_superadmin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 
    FROM user_profiles 
    WHERE id = auth.uid() 
    AND role = 'superuser'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.user_has_membership_in_org(org_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM organization_memberships
    WHERE user_id = auth.uid()
    AND organization_id = org_id
    AND is_active = true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.user_has_role_or_higher(required_role user_role)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 
    FROM user_profiles up
    WHERE up.id = auth.uid()
    AND (
      -- Superuser can do everything
      up.role = 'superuser' OR
      -- Regular role hierarchy
      (required_role = 'user' AND up.role IN ('user', 'admin', 'superuser')) OR
      (required_role = 'admin' AND up.role IN ('admin', 'superuser'))
    )
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_superuser()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 
    FROM user_profiles 
    WHERE id = auth.uid() 
    AND role = 'superuser'
  );
$function$
;

grant delete on table "public"."job_calendar_events" to "anon";

grant insert on table "public"."job_calendar_events" to "anon";

grant references on table "public"."job_calendar_events" to "anon";

grant select on table "public"."job_calendar_events" to "anon";

grant trigger on table "public"."job_calendar_events" to "anon";

grant truncate on table "public"."job_calendar_events" to "anon";

grant update on table "public"."job_calendar_events" to "anon";

grant delete on table "public"."job_calendar_events" to "authenticated";

grant insert on table "public"."job_calendar_events" to "authenticated";

grant references on table "public"."job_calendar_events" to "authenticated";

grant select on table "public"."job_calendar_events" to "authenticated";

grant trigger on table "public"."job_calendar_events" to "authenticated";

grant truncate on table "public"."job_calendar_events" to "authenticated";

grant update on table "public"."job_calendar_events" to "authenticated";

grant delete on table "public"."job_calendar_events" to "service_role";

grant insert on table "public"."job_calendar_events" to "service_role";

grant references on table "public"."job_calendar_events" to "service_role";

grant select on table "public"."job_calendar_events" to "service_role";

grant trigger on table "public"."job_calendar_events" to "service_role";

grant truncate on table "public"."job_calendar_events" to "service_role";

grant update on table "public"."job_calendar_events" to "service_role";

create policy "Users can access clients in their organizations"
on "public"."clients"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = clients.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = clients.organization_id) AND (om.is_active = true))))));


create policy "Users can access company in their organizations"
on "public"."company"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = company.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = company.organization_id) AND (om.is_active = true))))));


create policy "Users can access company_attachments in their organizations"
on "public"."company_attachments"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = company_attachments.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = company_attachments.organization_id) AND (om.is_active = true))))));


create policy "Users can access invoice_items in their organizations"
on "public"."invoice_items"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = invoice_items.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = invoice_items.organization_id) AND (om.is_active = true))))));


create policy "Users can access invoices in their organizations"
on "public"."invoices"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = invoices.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = invoices.organization_id) AND (om.is_active = true))))));


create policy "Allow delete for authenticated users"
on "public"."job_calendar_events"
as permissive
for delete
to public
using (true);


create policy "Allow insert for authenticated users"
on "public"."job_calendar_events"
as permissive
for insert
to public
with check (true);


create policy "Allow select for authenticated users"
on "public"."job_calendar_events"
as permissive
for select
to public
using (true);


create policy "Allow update for authenticated users"
on "public"."job_calendar_events"
as permissive
for update
to public
using (true);


create policy "Users can access job_calendar_events in their organizations"
on "public"."job_calendar_events"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = job_calendar_events.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = job_calendar_events.organization_id) AND (om.is_active = true))))));


create policy "Users can access job_costs in their organizations"
on "public"."job_costs"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = job_costs.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = job_costs.organization_id) AND (om.is_active = true))))));


create policy "Users can access jobs in their organizations"
on "public"."jobs"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = jobs.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = jobs.organization_id) AND (om.is_active = true))))));


create policy "Users can access jobs_attachments in their organizations"
on "public"."jobs_attachments"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = jobs_attachments.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = jobs_attachments.organization_id) AND (om.is_active = true))))));


create policy "Users can access materials in their organizations"
on "public"."materials"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = materials.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = materials.organization_id) AND (om.is_active = true))))));


create policy "Users can access services in their organizations"
on "public"."services"
as permissive
for all
to authenticated
using ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = services.organization_id) AND (om.is_active = true))))))
with check ((is_superuser() OR (EXISTS ( SELECT 1
   FROM organization_memberships om
  WHERE ((om.user_id = auth.uid()) AND (om.organization_id = services.organization_id) AND (om.is_active = true))))));


CREATE TRIGGER auto_set_org_id_clients BEFORE INSERT OR UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_company BEFORE INSERT OR UPDATE ON public.company FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_company_attachments BEFORE INSERT OR UPDATE ON public.company FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_invoice_items BEFORE INSERT OR UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_invoices BEFORE INSERT OR UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_job_calendar_events BEFORE INSERT OR UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_jobs BEFORE INSERT OR UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_jobs_costs BEFORE INSERT OR UPDATE ON public.materials FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_materials BEFORE INSERT OR UPDATE ON public.materials FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_jobs_attachments BEFORE INSERT OR UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();

CREATE TRIGGER auto_set_org_id_services BEFORE INSERT OR UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION auto_set_organization_id();


