-- HT-32: free-text notes on a client or on a job.
--
-- A note is a title and a body, written from the Notes entry under the
-- DOCUMENTATION heading of the client detail and job detail screens. A note
-- belongs to exactly one client or one job and disappears with it.
--
-- Access follows every other app table as it stands today: any signed-in user,
-- with an organization-scoped policy alongside so the table is ready for the
-- cross-organization lockdown deferred in 20260909200000_restrict_anon_access.
-- organization_id is stamped by the same trigger the other tables use.

create table if not exists "public"."notes" (
  "id" bigint generated by default as identity primary key,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone,
  "organization_id" uuid references "public"."organizations"("id") on delete cascade,
  "client_id" bigint references "public"."clients"("uid") on delete cascade,
  "job_id" bigint references "public"."jobs"("uid") on delete cascade,
  "title" text not null,
  "body" text not null default '',
  "created_by" uuid default auth.uid() references auth.users("id") on delete set null,
  constraint "notes_has_parent" check ("client_id" is not null or "job_id" is not null)
);

comment on table "public"."notes" is
  'HT-32: titled free-text notes shown under Documentation on a client or a job.';

create index if not exists "idx_notes_client_id" on "public"."notes" ("client_id");
create index if not exists "idx_notes_job_id" on "public"."notes" ("job_id");
create index if not exists "idx_notes_organization_id" on "public"."notes" ("organization_id");

alter table "public"."notes" enable row level security;

drop trigger if exists "auto_set_org_id_notes" on "public"."notes";
create trigger "auto_set_org_id_notes"
  before insert or update on "public"."notes"
  for each row execute function auto_set_organization_id();

-- Same effective access as the other app tables until the org lockdown lands.
drop policy if exists "Authenticated users can access notes" on "public"."notes";
create policy "Authenticated users can access notes"
  on "public"."notes"
  as permissive
  for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Users can access notes in their organizations" on "public"."notes";
create policy "Users can access notes in their organizations"
  on "public"."notes"
  as permissive
  for all
  to authenticated
  using (is_superuser() or exists (
    select 1 from organization_memberships om
    where om.user_id = auth.uid()
      and om.organization_id = notes.organization_id
      and om.is_active = true))
  with check (is_superuser() or exists (
    select 1 from organization_memberships om
    where om.user_id = auth.uid()
      and om.organization_id = notes.organization_id
      and om.is_active = true));

grant select, insert, update, delete on table "public"."notes" to authenticated;
grant all on table "public"."notes" to service_role;
